
CREATE TABLE EXAMEN_backup AS SELECT * FROM EXAMEN;

DROP TABLE EXAMEN;

SELECT 'Table EXAMEN supprimée' as Status;

CREATE TABLE EXAMEN AS SELECT * FROM EXAMEN_backup;

SELECT COUNT(*) as 'Examens restaurés' FROM EXAMEN;

DROP TABLE EXAMEN_backup;